version: '3'

services:
  data-export-php:
    environment:
      XDEBUG_CONFIG: "client_host=${DEV_HOST_IP} client_port=${XDEBUG_PORT} xdebug.mode=debug remote_connect_back=0"
      PHP_IDE_CONFIG: "serverName=${PHPSTORM_XDEBUG_HOST}"